# Run the Unit Tests
trigger:
- master
- dev

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: GOOGLE_STACKDRIVER
  - name:  modulePath
    value: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps: 
- task: GoTool@0
  inputs:
    version: '1.14'
- task: Go@0
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  inputs:
    command: 'build'
    workingDirectory: '$(system.defaultworkingdirectory)'
- task: CopyFiles@2
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop
# Download Google Cloud's key
- task: DownloadSecureFile@1
  name: gcloudkey # The name with which to reference the secure file's path on the agent, like $(gcloudkey.secureFilePath)
  inputs:
    secureFile: gcloud-key.json

- script: |
    cp '$(gcloudkey.secureFilePath)' .
  workingDirectory: '$(system.defaultworkingdirectory)'
  displayName: 'Installing Keys'

- task: Go@0
  inputs:
    command: 'test'
    arguments: '-v'
    workingDirectory: '$(system.defaultworkingdirectory)'